{
 "title": "Monthly Finances",
 "time": { "from": "2022-12-22T16:27:36.673Z", "to": "2024-03-18T01:55:47.910Z" },
 "templating": {
  "list": [
   {
    "name": "Periodo",
    "query": "WITH MRANGE AS (\n     SELECT DISTINCT\n         DATE_PART('YEAR', DATE) AS Year,\n         DATE_PART('MONTH', DATE) AS Month\n     FROM Fin.All_Expenses\n     ORDER BY Year, Month\n )\n\n SELECT CAST(MAKE_DATE(CAST(Year AS INT), CAST(Month AS INT), 3) AS TEXT) AS Date\n FROM MRANGE\nWHERE Year < DATE_PART('YEAR', CURRENT_DATE)\n    OR (Year = DATE_PART('YEAR', CURRENT_DATE)\n        AND Month <= DATE_PART('MONTH', CURRENT_DATE))"
   }
  ]
 },
 "panels": [
  { "title": "Dashboard Gastos", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Periodo" },
  {
   "title": "Balances",
   "type": "table",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT bank_name, SUM(amount)\nFROM fin.all_bank_postings\nWHERE currency = 'ARS'\nGROUP BY bank_name\nORDER BY 2 DESC, bank_name"
    }
   ]
  },
  {
   "title": "Liquidiez ARS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(amount)\nFROM fin.all_bank_postings\nWHERE currency = 'ARS'\n  AND DATE_PART('YEAR', DATE) <= DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n  AND DATE_PART('MONTH', DATE) <= DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))"
    }
   ]
  },
  {
   "title": "Liquidiez USD",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(amount)\nFROM fin.all_bank_postings\nWHERE currency = 'USD'\n  AND DATE_PART('YEAR', DATE) <= DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n  AND DATE_PART('MONTH', DATE) <= DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))"
    }
   ]
  },
  {
   "title": "Ratio Gastos Brutos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH IncomeSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Income\n    FROM\n        Fin.All_Income\n    GROUP BY\n        Y,\n        M\n),\nExpenseSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Expenses\n    FROM\n        Fin.All_Expenses\n    GROUP BY\n        Y,\n        M\n)\nSELECT\n    E.Expenses / I.Income * 100\nFROM\n    IncomeSum AS I\n    LEFT JOIN ExpenseSum AS E ON I.Y = E.Y\n        AND I.M = E.M\nWHERE\n    E.Y = DATE_PART(\n        'YEAR', TO_DATE(\n            '${Periodo}', 'YYYY-MM-DD'\n))\n    AND E.M = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n"
    }
   ]
  },
  {
   "title": "Gastos",
   "type": "table",
   "gridPos": { "h": 16, "w": 9, "x": 15, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT \n  Date AS Fecha, \n  CONCAT(Category, ' ⟶ ', Subcategory) AS Categoria,\n  Payee AS Quien,\n  Narration AS Descripcion,\n  Amount_usd AS Cantidad\nFROM fin.all_expenses\nWHERE\n  DATE_PART('YEAR', DATE) = DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n  AND DATE_PART('MONTH', DATE) = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\nORDER BY date ASC"
    }
   ]
  },
  {
   "title": "Gasto ARS",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount_ars)\nFROM\n  fin.all_expenses\nWHERE\n  DATE_PART('YEAR', DATE) = DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n  AND DATE_PART('MONTH', DATE) = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))"
    }
   ]
  },
  {
   "title": "Gasto USD",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SUM(amount_usd)\nFROM\n  fin.all_expenses\nWHERE\n  DATE_PART('YEAR', DATE) = DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n  AND DATE_PART('MONTH', DATE) = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))"
    }
   ]
  },
  {
   "title": "Ratio Gastos Brutos",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH IncomeSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Income\n    FROM\n        Fin.All_Income\n    WHERE\n        Origin = 'Job'\n    GROUP BY\n        Y,\n        M\n),\nExpenseSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Expenses\n    FROM\n        Fin.All_Expenses\n    WHERE\n        Subcategory != 'Comisiones'\n    GROUP BY\n        Y,\n        M\n)\nSELECT\n    E.Expenses / I.Income * 100\nFROM\n    IncomeSum AS I\n    LEFT JOIN ExpenseSum AS E ON I.Y = E.Y\n        AND I.M = E.M\nWHERE\n    E.Y = DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n    AND E.M = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n"
    }
   ]
  },
  {
   "title": "Gasto por cateogria",
   "type": "barchart",
   "gridPos": { "h": 19, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH UniqueCategories AS (\n    SELECT DISTINCT CATEGORY\n    FROM Fin.All_Expenses\n),\nExpensesForPeriod AS (\n    SELECT\n        CATEGORY,\n        SUM(Amount_usd) AS MonthlyExpense\n    FROM Fin.All_Expenses\n    WHERE\n        DATE_PART('YEAR', Date) = DATE_PART('YEAR', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n        AND DATE_PART('MONTH', Date) = DATE_PART('MONTH', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n    GROUP BY CATEGORY\n)\nSELECT\n    uc.CATEGORY,\n    COALESCE(efp.MonthlyExpense, 0) AS MonthlyExpense\nFROM UniqueCategories uc\nLEFT JOIN ExpensesForPeriod efp\n    ON uc.CATEGORY = efp.CATEGORY\nORDER BY MonthlyExpense DESC;\n"
    }
   ]
  },
  {
   "title": "Liquidiez USD",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 9, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "WITH IncomeSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Income\n    FROM\n        Fin.All_Income\n    GROUP BY\n        Y,\n        M\n),\nExpenseSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Expenses\n    FROM\n        Fin.All_Expenses\n    GROUP BY\n        Y,\n        M\n),\nNetIncomeSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Income\n    FROM\n        Fin.All_Income\n    WHERE\n        Origin = 'Job'\n    GROUP BY\n        Y,\n        M\n),\nNetExpenseSum AS (\n    SELECT\n        DATE_PART('YEAR', DATE) AS Y,\n        DATE_PART('MONTH', DATE) AS M,\n        SUM(Amount_Usd) AS Expenses\n    FROM\n        Fin.All_Expenses\n    WHERE\n        Subcategory != 'Comisiones'\n    GROUP BY\n        Y,\n        M\n)\nSELECT\n    MAKE_DATE(CAST(E.Y AS int), CAST(E.M AS int), 2) AS Date,\n    E.Expenses / I.Income * 100 AS RatioBruto,\n    NE.Expenses / NI.Income * 100 AS RatioNeto\nFROM\n    IncomeSum AS I\n    LEFT JOIN ExpenseSum AS E ON I.Y = E.Y\n        AND I.M = E.M\n    LEFT JOIN NetIncomeSum AS NI ON I.Y = NI.Y\n        AND I.M = NI.M\n    LEFT JOIN NetExpenseSum AS NE ON I.Y = NE.Y\n        AND I.M = NE.M\nWHERE\n    E.Y < DATE_PART('YEAR', CURRENT_DATE)\n    OR (E.Y = DATE_PART('YEAR', CURRENT_DATE)\n        AND E.M <= DATE_PART('MONTH', CURRENT_DATE))\nORDER BY\n    DATE ASC\n"
    }
   ]
  },
  {
   "title": "Gastos en contexto",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 9, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "WITH UniqueCategories AS (\n    SELECT DISTINCT CATEGORY\n    FROM Fin.All_Expenses\n),\nUniqueMonths AS (\n    SELECT DISTINCT\n        EXTRACT(YEAR FROM Date) AS Y,\n        EXTRACT(MONTH FROM Date) AS M\n    FROM Fin.All_Expenses\n    WHERE\n        EXTRACT(YEAR FROM Date) <= EXTRACT(YEAR FROM TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n        AND EXTRACT(MONTH FROM Date) <= EXTRACT(MONTH FROM TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n),\nCrossJoined AS (\n    SELECT\n        Uc.CATEGORY,\n        Um.Y,\n        Um.M\n    FROM UniqueCategories AS Uc\n    CROSS JOIN UniqueMonths AS Um\n),\nAggregatedExpenses AS (\n    SELECT\n        CATEGORY,\n        EXTRACT(YEAR FROM Date) AS Y,\n        EXTRACT(MONTH FROM Date) AS M,\n        SUM(Amount_usd) AS MonthlyExpense\n    FROM Fin.All_Expenses\n    GROUP BY CATEGORY, Y, M\n),\nCurrentMonthExpenses AS (\n    SELECT\n        CATEGORY,\n        SUM(Amount_usd) AS Actual\n    FROM Fin.All_Expenses\n    WHERE\n        Date >= DATE_TRUNC('month', TO_DATE('${Periodo}', 'YYYY-MM-DD'))\n        AND Date < DATE_TRUNC('month', TO_DATE('${Periodo}', 'YYYY-MM-DD')) + INTERVAL '1 month'\n    GROUP BY CATEGORY\n),\nMonthly AS (\n    SELECT\n        Cj.CATEGORY,\n        Cj.Y,\n        Cj.M,\n        COALESCE(Ae.MonthlyExpense, 0) AS MonthlyExpense\n    FROM CrossJoined AS Cj\n    LEFT JOIN AggregatedExpenses AS Ae\n        ON Cj.CATEGORY = Ae.CATEGORY AND Cj.Y = Ae.Y AND Cj.M = Ae.M\n    ORDER BY Cj.CATEGORY, Cj.Y, Cj.M\n)\nSELECT\n    M.CATEGORY,\n    COALESCE(CME.Actual, 0) AS Actual,\n    ROUND(AVG(M.MonthlyExpense), 2) AS Promedio\n    --PERCENTILE_CONT(0.5) WITHIN GROUP (\n    --    ORDER BY M.MonthlyExpense\n    --) AS Mediana\nFROM\n    Monthly M\nLEFT JOIN CurrentMonthExpenses CME ON M.CATEGORY = CME.CATEGORY\nGROUP BY\n    M.CATEGORY,\n    CME.Actual\nORDER BY\n    M.CATEGORY;\n"
    }
   ]
  }
 ]
}